use_frameworks!

target 'EFNavigationBar_Example' do
  pod 'EFNavigationBar', :path => '../'
  pod 'WRCycleScrollView', :git => 'https://github.com/EFRenovation/WRCycleScrollView.git'

  target 'EFNavigationBar_Tests' do
    inherit! :search_paths

    
  end
end
