use_frameworks!
platform :ios, '8.0'

target 'EFNavigationBar_Example' do
  pod 'EFNavigationBar', :path => '../'
  
  target 'EFNavigationBar_Tests' do
    inherit! :search_paths
    
    
  end
end
